name: Mirror and run GitLab CI

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow cloning
      - name: Configure Git
        run: |
          git config user.name "CBMcArthur2"
          git config user.email "cbmcarthur2@gmail.coim"
      - name: Mirror to GitLab
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
        run: |
          git remote add gitlab https://cbmcarthur:${{ secrets.GL_TOKEN }}@gitlab.com/cbmcarthur/dbwrapper.git
          git update-ref -d refs/remotes/origin/main
          git remote -v
          git show-ref
          git push --mirror gitlab
